# -*- coding: utf-8 -*-
"""Fractal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JgrU-JZf1NrpP_nxNUvFiIRhXXiSP1wE
"""

import numpy as np
import matplotlib.pyplot as plt

def julia_set(width, height, x_min, x_max, y_min, y_max, c, max_iter):
    x, y = np.linspace(x_min, x_max, width), np.linspace(y_min, y_max, height)
    X, Y = np.meshgrid(x, y)
    Z = X + 1j * Y
    image = np.zeros(Z.shape, dtype=float)

    for i in range(max_iter):
        Z = Z**2 + c
        mask = np.abs(Z) < 1000
        image += mask

    return image

def plot_julia_set(image):
    plt.imshow(image, cmap='viridis', extent=(x_min, x_max, y_min, y_max))
    plt.colorbar()
    plt.title('Julia Set')
    plt.xlabel('Real')
    plt.ylabel('Imaginary')
    plt.show()

# Set parameters
width, height = 3200, 3200
x_min, x_max = -2, 2
y_min, y_max = -2, 2
c = -0.8 + 0.156j  # this complex constant is changable to generate different Julia sets
max_iter = 100

# Generate and plot Julia set
julia_image = julia_set(width, height, x_min, x_max, y_min, y_max, c, max_iter)
plot_julia_set(julia_image)

from PIL import Image
import numpy as np

def julia_set(width, height, x_min, x_max, y_min, y_max, c, max_iter):
    x, y = np.linspace(x_min, x_max, width), np.linspace(y_min, y_max, height)
    X, Y = np.meshgrid(x, y)
    Z = X + 1j * Y
    image = np.zeros(Z.shape, dtype=float)

    for i in range(max_iter):
        Z = Z**2 + c
        mask = np.abs(Z) < 1000
        image += mask

    return image

def create_image_array(image, cmap='viridis'):
    norm_image = (image - np.min(image)) / (np.max(image) - np.min(image))
    rgba_image = plt.get_cmap(cmap)(norm_image)
    return (rgba_image[:, :, :3] * 255).astype(np.uint8)

def save_image(image_array, file_path):
    im = Image.fromarray(image_array)
    im.save(file_path)

# Set parameters
width, height = 6400, 6400
x_min, x_max = -2, 2
y_min, y_max = -2, 2
c = -0.8 + 0.156j  # this complex constant is changable to generate different Julia sets
max_iter = 100

# Generate Julia set
julia_image = julia_set(width, height, x_min, x_max, y_min, y_max, c, max_iter)

# Create and save image
image_array = create_image_array(julia_image)
save_image(image_array, 'julia_set.png')